[project]
name = "conversion-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ai2-olmo-core[fla]>=2.4.0",
    "torch==2.11.0+cu128",
    "transformers>=5.9.0",
]

[tool.uv.sources]
ai2-olmo-core = { git = "https://github.com/jopetty/OLMo-core.git", rev = "ppt" }
transformers = { git = "https://github.com/YashasSamaga/transformers.git", rev = "hybrid-small-suite" }
torch = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[dependency-groups]
dev = [
    "ruff>=0.15.16",
    "ty>=0.0.44",
]
