[project]
name = "conversion-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "torch>=2.12.0",
    "transformers>=5.9.0",
]

[tool.uv.sources]
transformers = { git = "https://github.com/YashasSamaga/transformers.git", rev = "hybrid-small-suite" }

[dependency-groups]
dev = [
    "ruff>=0.15.16",
]
